# -*- coding: utf-8 -*-
"""
Agent-OS-Kernel - AI Agent 的操作系统内核
"""

__version__ = "0.2.0"
__author__ = "Bit-Cook"
__license__ = "MIT"

# Core modules
from .core import (
    LatencyResult,
    ThroughputResult,
    ResourceUsage,
    LatencyBenchmark,
    ThroughputBenchmark,
    ResourceMonitor,
    PerformanceReport,
    PerformanceBenchmark,
    measure_latency,
    measure_throughput,
    monitor_resources,
    generate_report,
    # Message Queue modules
    Message,
    MessagePriority,
    MessageStatus,
    PriorityMessageQueue,
    MessageBroker,
    Subscription,
    create_message_broker,
    # Optimizer模块有语法错误，暂时禁用
    # PoolConfig,
    # CacheConfig,
    # ConcurrencyConfig,
    # ConnectionPool,
    # LRUCache,
    # ThreadPoolOptimizer,
    # MemoryOptimizer,
    # ConcurrencyLimiter,
    # BatchProcessor,
    # create_connection_pool,
    # create_lru_cache,
    # create_thread_pool,
    # create_memory_pool,
    # create_concurrency_limiter,
    # create_batch_processor,
    # Service Mesh
    CircuitState,
    LoadBalancingStrategy,
    ServiceInstance,
    ServiceInfo,
    CircuitBreaker,
    CircuitBreakerOpen,
    ServiceRegistry,
    LoadBalancer,
    ServiceClient,
    ServiceNotFound,
    NoHealthyInstance,
    ServiceMesh,
    create_service_mesh,
    create_service_registry,
    create_load_balancer,
    create_circuit_breaker,
    # Workflow Engine
    WorkflowEngine,
    Workflow,
    Task,
    TaskConfig,
    TaskStatus,
    WorkflowStatus,
    TaskResult,
    create_workflow_engine,
    # Distributed Lock
    LockType,
    LockState,
    LockOwner,
    LockAcquireError,
    LockRenewalError,
    LockTimeoutError,
    DistributedLockBackend,
    InMemoryLockBackend,
    ReadWriteLockBackend,
    DistributedLock,
    ReadWriteLock,
    create_distributed_lock,
    create_read_write_lock,
)

__all__ = [
    "__version__",
    "__author__",
    "__license__",
    # Benchmark
    "LatencyResult",
    "ThroughputResult",
    "ResourceUsage",
    "LatencyBenchmark",
    "ThroughputBenchmark",
    "ResourceMonitor",
    "PerformanceReport",
    "PerformanceBenchmark",
    "measure_latency",
    "measure_throughput",
    "monitor_resources",
    "generate_report",
    # Message Queue
    "Message",
    "MessagePriority",
    "MessageStatus",
    "PriorityMessageQueue",
    "MessageBroker",
    "Subscription",
    "create_message_broker",
    # Optimizer (disabled due to syntax errors)
    # "PoolConfig",
    # "CacheConfig",
    # "ConcurrencyConfig",
    # "ConnectionPool",
    # "LRUCache",
    # "ThreadPoolOptimizer",
    # "MemoryOptimizer",
    # "ConcurrencyLimiter",
    # "BatchProcessor",
    # "create_connection_pool",
    # "create_lru_cache",
    # "create_thread_pool",
    # "create_memory_pool",
    # "create_concurrency_limiter",
    # "create_batch_processor",
    # Service Mesh
    "CircuitState",
    "LoadBalancingStrategy",
    "ServiceInstance",
    "ServiceInfo",
    "CircuitBreaker",
    "CircuitBreakerOpen",
    "ServiceRegistry",
    "LoadBalancer",
    "ServiceClient",
    "ServiceNotFound",
    "NoHealthyInstance",
    "ServiceMesh",
    "create_service_mesh",
    "create_service_registry",
    "create_load_balancer",
    "create_circuit_breaker",
    # Workflow Engine
    "WorkflowEngine",
    "Workflow",
    "Task",
    "TaskConfig",
    "TaskStatus",
    "WorkflowStatus",
    "TaskResult",
    "create_workflow_engine",
    # Distributed Lock
    "LockType",
    "LockState",
    "LockOwner",
    "LockAcquireError",
    "LockRenewalError",
    "LockTimeoutError",
    "DistributedLockBackend",
    "InMemoryLockBackend",
    "ReadWriteLockBackend",
    "DistributedLock",
    "ReadWriteLock",
    "create_distributed_lock",
    "create_read_write_lock",
]
